updaten cdk toolkit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,13 +53,27 @@ jobs:
         run: cdk synth
         working-directory: s3_resource
 
-      - name: cdk bootstrap
-        run: cdk bootstrap
-        working-directory: s3_resource
+      # - name: cdk bootstrap
+      #   run: cdk bootstrap
+      #   working-directory: s3_resource
+
+      - name: Check if CDK Toolkit is present in the region
+        id: check_cdk_toolkit
+        run: |
+          export BOOTSTRAP_STACK_NAME="CDKToolkit"
+          export CDK_DEPLOY_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
+          export CDK_DEPLOY_REGION=$(aws configure get region)
+
+          aws cloudformation describe-stacks --stack-name $BOOTSTRAP_STACK_NAME --query 'Stacks[].StackId' --region $CDK_DEPLOY_REGION --output text || echo "CDKToolkit not found in region"
+          echo ::set-output name=cdk_toolkit_found::$(aws cloudformation describe-stacks --stack-name $BOOTSTRAP_STACK_NAME --query 'Stacks[].StackId' --region $CDK_DEPLOY_REGION --output text)
 
 
       - name: cdk deploy
-        run: cdk deploy
+        run: |
+         if [[ -z "${{ steps.check_cdk_toolkit.outputs.cdk_toolkit_found }}" ]]; then
+          cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
+         fi
+         cdk deploy --require-approval never
         working-directory: s3_resource  
 
 
